
export const UPDATE_BREWERIES = "UPDATE_BREWERIES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const CLEAR_FAVORITES = "CLEAR_FAVORITES";
export const TOGGLE_FAVORITES = "TOGGLE_FAVORITES";
